import { useEffect, useState } from 'react'
import Head from 'next/head'
import JSZip from 'jszip'
import FileSaver from 'file-saver'
import { Header } from '@modules/Header/Header'
import { IconList } from '@modules/IconList/IconList'
import { icons } from '@icons/icons'
import styles from '@styles/Home.module.css'

const getColorScheme = () =>
	typeof window !== 'undefined' &&
	window.matchMedia('(prefers-color-scheme: dark)').matches
		? 'dark'
		: 'light'

export default function Home() {
	const [color, setColor] = useState(() => '#ffffff')
	const [strokeWidth, setStrokeWidth] = useState('2')
	const [size, setSize] = useState('24')

	const handleOnDownload = () => {
		const zip = new JSZip()

		icons.forEach(file => {
			zip.file(`${file.name}.svg`, file.svg(color, strokeWidth, size))
		})

		zip.generateAsync({ type: 'blob' }).then(function (content) {
			FileSaver.saveAs(content, 'polkadot-icons.zip')
		})
	}

	useEffect(() => {
		// prevents hydration error when in light mode
		setColor(getColorScheme() === 'dark' ? '#ffffff' : '#000000')
	}, [])

	return (
		<div className={styles.container}>
			<Head>
				<title>Polkadot Icons</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="preload"
					href="/Unbounded-Regular.woff2"
					as="font"
					type="font/woff2"
					crossOrigin="anonymous"
				/>
				<link
					rel="preload"
					href="/Unbounded-Bold.woff2"
					as="font"
					type="font/woff2"
					crossOrigin="anonymous"
				/>
			</Head>
			<main className={styles.main}>
				<Header
					colorState={[color, setColor]}
					strokeWidthState={[strokeWidth, setStrokeWidth]}
					sizeState={[size, setSize]}
				/>

				<IconList {...{ color, size, strokeWidth }} />

				<button className={styles.buttonOutline} onClick={handleOnDownload}>
					Download all
				</button>
			</main>
		</div>
	)
}
